"""Generate the frontend manual-entry catalog from the backend authority file."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data/reference/analyte_catalog.json"
TARGET = ROOT / "frontend/src/generated/analyteCatalog.mjs"


def render_catalog() -> str:
    payload = json.loads(SOURCE.read_text(encoding="utf-8"))
    approved = [
        entry for entry in payload["entries"] if entry["runtime_status"] == "APPROVED"
    ]
    lines = [
        "// Generated by scripts/generate_frontend_analyte_catalog.py.",
        "// Do not edit manually; data/reference/analyte_catalog.json is authoritative.",
        f'export const ANALYTE_CATALOG_VERSION = "{payload["catalog_version"]}";',
        "export const GENERATED_MANUAL_ANALYTES = Object.freeze([",
    ]
    for entry in approved:
        values = {
            "name": entry["canonical_name"],
            "unit": entry["canonical_unit"],
            "analyteId": entry["analyte_id"],
            "canonicalGroup": entry["group"],
            "runtimeStatus": entry["runtime_status"],
        }
        rendered = ", ".join(
            f"{key}: {json.dumps(value, ensure_ascii=False)}"
            for key, value in values.items()
        )
        lines.append(f"  {{ {rendered} }},")
    lines.extend(["]);", ""])
    return "\n".join(lines)


def main() -> None:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(render_catalog(), encoding="utf-8")


if __name__ == "__main__":
    main()
